### ISSUE TITLE
Segfaults when trying to download/upload something.

### ISSUE THREAD

**Issue by baduhai** [MarceColl/zen-browser-flake#4]
Looks like either some dependency is missing from the derivation, or something wasn't properly patched with patchelf.

This is the console output when I try to download something:

```
[Parent 44952, Main Thread] ###!!! ASSERTION: No GSettings schemas are installed on the system: 'glib assertion', file /home/runner/work/desktop/desktop/engine/toolkit/xre/nsSigHandlers.cpp:184

(zen-alpha:44952): GLib-GIO-ERROR **: 19:45:07.516: No GSettings schemas are installed on the system
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=6.1323) Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5.93381) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=6.12391) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Exiting due to channel error.
fish: Job 1, 'zen' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

This issue is not present in the appimage.

**Comment by MarceColl** [comment]
can you give more info about your system? it seems like you don't have XDG_DATA_DIRS correctly setup.

**Comment by MarceColl** [comment]
I've pushed an update that may fix it for you, it seems that GTK apps need to be wrapped using `wrapGAppsHook` for gsettings schemas to be populated. It seems this is not completely reproducible in each environment since I already have it populated because I probably have some other apps doing the same already and you may not. Try the new version I just pushed with 0ecc25c and let me know if it works for you.

**Comment by baduhai** [comment]
Still doesn't seem to work, same error message as above, I'll stick to the appimage for now.

I had to fix the hash for the flake to work, as it seem yo forgot to when yo updated the package to 1.0.0-a.27. The new hash is `sha256:0vmn10qpr96b4i8j24sa6ipg3fcxiiigkjwclbr5fknkfj3r6ds7`.

I just let nixos take care of XDG, `echo $XDG_DATA_DIRS` returns:

`/nix/store/3zg1njfzha4w9c00a081ckg9qhialp97-kwin-6.1.4/share /nix/store/2ak5z6fv58pb8vdwwg5v9wjy7fkxwjm3-kscreenlocker-6.1.4/share /nix/store/zs9cvyk6b0dzgmxn9fkfl2f0aqgjwm9l-libplasma-6.1.4/share /nix/store/yyiqydynbjhfr38mpsxzdaai618nhcx1-kparts-6.5.0/share /nix/store/c5jj4vm35q3zh4cy18cgw6122254v3jc-libkscreen-6.1.4/share /nix/store/65jkmzaqb0fvg2ij9fsq3980cd6f4a0v-kpipewire-6.1.4/share /nix/store/jv1bwib66y6x52zs7g7b92p7ad8l0pq8-kdeclarative-6.5.0/share /nix/store/fa2z8nijz4zm8d1h31095ww1z77pzh6z-breeze-6.1.4/share /nix/store/cbbc1vbj1w41x7lf7qr24hq9j48p0k9h-kdecoration-6.1.4/share /nix/store/c600crw2gcpinwxsjqy9a1866fjzn6q3-frameworkintegration-6.5.0/share /nix/store/smcqi8bppk618r2bbclwav6admc23c1h-oxygen-icons-6.0.0/share /nix/store/jhpsjchp2pjbg7k858rchzcbq5m4v3rh-knewstuff-6.5.0/share /nix/store/q68virr0lv0s2aik4grgz211v46q7f5s-kcmutils-6.5.0/share /nix/store/0wv0mymvcjz563xwmydvmv9d0rpymbcm-kxmlgui-6.5.0/share /nix/store/gnyg0d0i93lmhm4jd7xwkn39lzba7pb3-ktextwidgets-6.5.0/share /nix/store/pdv30g39kp1br9yhms8qhwczimim5xwl-kglobalaccel-6.5.0/share /nix/store/dqdra335l1736w2p0gmanzl1xbyh7m6c-kpackage-6.5.0/share /nix/store/ql0rcvm5x0hy7wwlbwj2dyx17a7mxw6f-qqc2-desktop-style-6.5.0/share /nix/store/7chb7jxzkk3j30l0yz1489dxb918iji0-sonnet-6.5.0/share /nix/store/5kma93snq7jphs9s80iskhczlfqn1v5z-kirigami-6.5.0/share /nix/store/ssqm007ad4lsz1k3v4vq8fyqvf06a1pl-kio-6.5.0/share /nix/store/an92bay55zr8gslbh2pw10h89kkly0rv-solid-6.5.0/share /nix/store/az9vjz0pblhkm3013s1ghlk6kcrc6xbj-kwallet-6.5.0/share /nix/store/zksfmy1qijfm5gszvvmxsqcl0d74k5yz-libgpg-error-1.50/share /nix/store/ijdl5kgc40xkwdjzwlmf17w6yxrhyyq6-kservice-6.5.0/share /nix/store/swd2d1pc4r5bgj87zxkh0ax28kx0z28x-kjobwidgets-6.5.0/share /nix/store/ic14hwn5gfqy5s81kadph0qskqrfj97w-knotifications-6.5.0/share /nix/store/wg3qw25z1rihr830hnc80axac5337g74-kitemviews-6.5.0/share /nix/store/8vic35xc2ncy42277540xw9rj9g4s6df-kdoctools-6.5.0/share /nix/store/5yi4vwpx1321gmr90fxsw3qlq3b244bl-kdbusaddons-6.5.0/share /nix/store/0l4a2mg6r9zzivnia4ddaf0zy4bwnid2-kcompletion-6.5.0/share /nix/store/874c7bilzdf3xr4fyiz9h2vqihj310ig-kbookmarks-6.5.0/share /nix/store/7ix5kji7frzbhjhlhfj6v3xizplpjp1k-kauth-6.5.0/share /nix/store/wcpa02nq9d3jpxw6pykj8khlbrvf4s2c-kwindowsystem-6.5.0/share /nix/store/32la1z4byllm4ci5q4vl0j2w2hnkl2zy-kiconthemes-6.5.0/share /nix/store/7jbwmfdqcgkzn7ms99hnvzfa912i7lj3-karchive-6.5.0/share /nix/store/7vcz5xwa48dymc5ph92qm83zrkzgi6p4-breeze-icons-6.5.0/share /nix/store/8d1780gd681p992jjlil51g6v0adfgg1-kconfigwidgets-6.5.0/share /nix/store/7rqgyvpn01aspyjx6fjp8drsi5rxhsq4-kwidgetsaddons-6.5.0/share /nix/store/xaq2rsh24p13m0d5g00szmiarhg3iy13-kcodecs-6.5.0/share /nix/store/d4hfrza2csgr2nzgrbdqhh4n3hy6q8md-kcolorscheme-6.5.0/share /nix/store/hb1hkfsscqzqjfra32n99nf9wjwbq6hx-appstream-qt-1.0.3/share /nix/store/m1ykzddkgwz4w5b6zzghvqkzykbbl9rn-pipewire-1.2.2/share /nix/store/yd9mkrx6zsrhy7zy81iwfzzbp45yshql-attr-2.5.2/share /nix/store/z6mr5r2qs297lj8jy2vfy2p8qnsjy3sf-xz-5.6.2/share /nix/store/6gfsg2hh7wzz1ms05ix9ik201y5clx7j-ki18n-6.5.0/share /nix/store/k7f40g0fqwmzdwbqnlh5ss18v73fp34b-kcoreaddons-6.5.0/share /nix/store/v6k9fn04xfhv74pv86s0k3bjdnz06382-kconfig-6.5.0/share /nix/store/82yjal0y00na3swm0licw56ia61yqk73-hunspell-1.7.2/share /nix/store/pm0dm1g5hpcl9dpinqlzzkhf200jghp3-fontconfig-2.15.0-lib/share /nix/store/fs7lnqjn3zix2g3iz2b3ynf2m3rh4vcv-util-linux-2.39.4-lib/share /nix/store/mhq3m0gm80w8xxkbbkhds2gcm2k7y4fd-systemd-256.4/share /nix/store/7lr9qdizm42pf6clysg7syrky0si8aab-glib-2.80.4/share /nix/store/5i7vyd1n23g84fljnp9y80yvz6b7k9c4-gettext-0.21.1/share /nix/store/3zg1njfzha4w9c00a081ckg9qhialp97-kwin-6.1.4/share /nix/store/2ak5z6fv58pb8vdwwg5v9wjy7fkxwjm3-kscreenlocker-6.1.4/share /nix/store/zs9cvyk6b0dzgmxn9fkfl2f0aqgjwm9l-libplasma-6.1.4/share /nix/store/yyiqydynbjhfr38mpsxzdaai618nhcx1-kparts-6.5.0/share /nix/store/c5jj4vm35q3zh4cy18cgw6122254v3jc-libkscreen-6.1.4/share /nix/store/65jkmzaqb0fvg2ij9fsq3980cd6f4a0v-kpipewire-6.1.4/share /nix/store/jv1bwib66y6x52zs7g7b92p7ad8l0pq8-kdeclarative-6.5.0/share /nix/store/fa2z8nijz4zm8d1h31095ww1z77pzh6z-breeze-6.1.4/share /nix/store/cbbc1vbj1w41x7lf7qr24hq9j48p0k9h-kdecoration-6.1.4/share /nix/store/c600crw2gcpinwxsjqy9a1866fjzn6q3-frameworkintegration-6.5.0/share /nix/store/smcqi8bppk618r2bbclwav6admc23c1h-oxygen-icons-6.0.0/share /nix/store/jhpsjchp2pjbg7k858rchzcbq5m4v3rh-knewstuff-6.5.0/share /nix/store/q68virr0lv0s2aik4grgz211v46q7f5s-kcmutils-6.5.0/share /nix/store/0wv0mymvcjz563xwmydvmv9d0rpymbcm-kxmlgui-6.5.0/share /nix/store/gnyg0d0i93lmhm4jd7xwkn39lzba7pb3-ktextwidgets-6.5.0/share /nix/store/pdv30g39kp1br9yhms8qhwczimim5xwl-kglobalaccel-6.5.0/share /nix/store/dqdra335l1736w2p0gmanzl1xbyh7m6c-kpackage-6.5.0/share /nix/store/ql0rcvm5x0hy7wwlbwj2dyx17a7mxw6f-qqc2-desktop-style-6.5.0/share /nix/store/7chb7jxzkk3j30l0yz1489dxb918iji0-sonnet-6.5.0/share /nix/store/5kma93snq7jphs9s80iskhczlfqn1v5z-kirigami-6.5.0/share /nix/store/ssqm007ad4lsz1k3v4vq8fyqvf06a1pl-kio-6.5.0/share /nix/store/an92bay55zr8gslbh2pw10h89kkly0rv-solid-6.5.0/share /nix/store/az9vjz0pblhkm3013s1ghlk6kcrc6xbj-kwallet-6.5.0/share /nix/store/zksfmy1qijfm5gszvvmxsqcl0d74k5yz-libgpg-error-1.50/share /nix/store/ijdl5kgc40xkwdjzwlmf17w6yxrhyyq6-kservice-6.5.0/share /nix/store/swd2d1pc4r5bgj87zxkh0ax28kx0z28x-kjobwidgets-6.5.0/share /nix/store/ic14hwn5gfqy5s81kadph0qskqrfj97w-knotifications-6.5.0/share /nix/store/wg3qw25z1rihr830hnc80axac5337g74-kitemviews-6.5.0/share /nix/store/8vic35xc2ncy42277540xw9rj9g4s6df-kdoctools-6.5.0/share /nix/store/5yi4vwpx1321gmr90fxsw3qlq3b244bl-kdbusaddons-6.5.0/share /nix/store/0l4a2mg6r9zzivnia4ddaf0zy4bwnid2-kcompletion-6.5.0/share /nix/store/874c7bilzdf3xr4fyiz9h2vqihj310ig-kbookmarks-6.5.0/share /nix/store/7ix5kji7frzbhjhlhfj6v3xizplpjp1k-kauth-6.5.0/share /nix/store/wcpa02nq9d3jpxw6pykj8khlbrvf4s2c-kwindowsystem-6.5.0/share /nix/store/32la1z4byllm4ci5q4vl0j2w2hnkl2zy-kiconthemes-6.5.0/share /nix/store/7jbwmfdqcgkzn7ms99hnvzfa912i7lj3-karchive-6.5.0/share /nix/store/7vcz5xwa48dymc5ph92qm83zrkzgi6p4-breeze-icons-6.5.0/share /nix/store/8d1780gd681p992jjlil51g6v0adfgg1-kconfigwidgets-6.5.0/share /nix/store/7rqgyvpn01aspyjx6fjp8drsi5rxhsq4-kwidgetsaddons-6.5.0/share /nix/store/xaq2rsh24p13m0d5g00szmiarhg3iy13-kcodecs-6.5.0/share /nix/store/d4hfrza2csgr2nzgrbdqhh4n3hy6q8md-kcolorscheme-6.5.0/share /nix/store/hb1hkfsscqzqjfra32n99nf9wjwbq6hx-appstream-qt-1.0.3/share /nix/store/m1ykzddkgwz4w5b6zzghvqkzykbbl9rn-pipewire-1.2.2/share /nix/store/yd9mkrx6zsrhy7zy81iwfzzbp45yshql-attr-2.5.2/share /nix/store/z6mr5r2qs297lj8jy2vfy2p8qnsjy3sf-xz-5.6.2/share /nix/store/6gfsg2hh7wzz1ms05ix9ik201y5clx7j-ki18n-6.5.0/share /nix/store/k7f40g0fqwmzdwbqnlh5ss18v73fp34b-kcoreaddons-6.5.0/share /nix/store/v6k9fn04xfhv74pv86s0k3bjdnz06382-kconfig-6.5.0/share /nix/store/82yjal0y00na3swm0licw56ia61yqk73-hunspell-1.7.2/share /nix/store/pm0dm1g5hpcl9dpinqlzzkhf200jghp3-fontconfig-2.15.0-lib/share /nix/store/fs7lnqjn3zix2g3iz2b3ynf2m3rh4vcv-util-linux-2.39.4-lib/share /nix/store/mhq3m0gm80w8xxkbbkhds2gcm2k7y4fd-systemd-256.4/share /nix/store/7lr9qdizm42pf6clysg7syrky0si8aab-glib-2.80.4/share /nix/store/5i7vyd1n23g84fljnp9y80yvz6b7k9c4-gettext-0.21.1/share /nix/store/cl36slx7ap364f9vyrc2d70kav4hwlv9-plasma-workspace-6.1.4/share /nix/store/d0yfbqbnpkyfsyibvsky1d8k5954ldba-plasma5support-6.1.4/share /nix/store/z23fv0y0jgcl5mdj14v6a477fbpplvgd-plasma-nano-6.1.4/share /nix/store/x1bqs5q3pkf525y2x2bh6dnj7qh509li-networkmanager-1.48.8/share /nix/store/p9d3qcqvx19a6fcvq9kbg4nbipmfjs3g-gnutls-3.8.6/share /nix/store/85p80sm1i3xg1cqajgis6hdq9ydm3zg1-milou-6.1.4/share /nix/store/lllls9945303m5mcyqydivfp20i4m707-libksysguard-6.1.4/share /nix/store/3zg1njfzha4w9c00a081ckg9qhialp97-kwin-6.1.4/share /nix/store/fa2z8nijz4zm8d1h31095ww1z77pzh6z-breeze-6.1.4/share /nix/store/cbbc1vbj1w41x7lf7qr24hq9j48p0k9h-kdecoration-6.1.4/share /nix/store/c600crw2gcpinwxsjqy9a1866fjzn6q3-frameworkintegration-6.5.0/share /nix/store/smcqi8bppk618r2bbclwav6admc23c1h-oxygen-icons-6.0.0/share /nix/store/dxsisspg3ihlqlrn2mlr4n9n5r5mnbxk-kuserfeedback-6.5.0/share /nix/store/yxzili610n3lbbj3mz3jwmp43yz03li8-kunitconversion-6.5.0/share /nix/store/10z0mq5z3zibsjlr1iksx4j017zmar3f-ktexteditor-6.5.0/share /nix/store/gcg97w8pwjp9fv80h8wnj0770vqddnh7-kstatusnotifieritem-6.5.0/share /nix/store/2ak5z6fv58pb8vdwwg5v9wjy7fkxwjm3-kscreenlocker-6.1.4/share /nix/store/zs9cvyk6b0dzgmxn9fkfl2f0aqgjwm9l-libplasma-6.1.4/share /nix/store/c5jj4vm35q3zh4cy18cgw6122254v3jc-libkscreen-6.1.4/share /nix/store/65jkmzaqb0fvg2ij9fsq3980cd6f4a0v-kpipewire-6.1.4/share /nix/store/yyiqydynbjhfr38mpsxzdaai618nhcx1-kparts-6.5.0/share /nix/store/48f9118lx5zp7v0sgv4cnwb3i687xvjy-knotifyconfig-6.5.0/share /nix/store/jhpsjchp2pjbg7k858rchzcbq5m4v3rh-knewstuff-6.5.0/share /nix/store/dqdra335l1736w2p0gmanzl1xbyh7m6c-kpackage-6.5.0/share /nix/store/aj475bw34pm2c307hnh5sars7kxx5ji8-kirigami-addons-1.4.0/share /nix/store/wsy3rb4hmxr0c7d9ihlzxz3rdxvvxc72-kio-extras-24.05.2/share /nix/store/jvifh5hkz1aiwy9lh4v8lcgmyw01hqwn-syntax-highlighting-6.5.0/share /nix/store/mymnfc6bnhlvby8xz8ijmbfjjcmddbgj-phonon-4.12.0/share /nix/store/xkxxys1qwxlj9gd7amqp4r03vcn6q1k9-kdnssd-6.5.0/share /nix/store/0pnk7ll379brx262pcyymdl06ia9bj6c-kholidays-6.5.0/share /nix/store/kjfvcs04sjimng4dv6fpnnwwc2hbqzkj-kdesu-6.5.0/share /nix/store/f8c92zncrc6nyw75jspdl580r3dcwnka-kpty-6.5.0/share /nix/store/jv1bwib66y6x52zs7g7b92p7ad8l0pq8-kdeclarative-6.5.0/share /nix/store/q68virr0lv0s2aik4grgz211v46q7f5s-kcmutils-6.5.0/share /nix/store/0wv0mymvcjz563xwmydvmv9d0rpymbcm-kxmlgui-6.5.0/share /nix/store/gnyg0d0i93lmhm4jd7xwkn39lzba7pb3-ktextwidgets-6.5.0/share /nix/store/pdv30g39kp1br9yhms8qhwczimim5xwl-kglobalaccel-6.5.0/share /nix/store/6fwqrz1j5cqn7fjk1ar9lfna5bjam1ry-baloo-6.5.0/share /nix/store/ssqm007ad4lsz1k3v4vq8fyqvf06a1pl-kio-6.5.0/share /nix/store/an92bay55zr8gslbh2pw10h89kkly0rv-solid-6.5.0/share /nix/store/az9vjz0pblhkm3013s1ghlk6kcrc6xbj-kwallet-6.5.0/share /nix/store/zksfmy1qijfm5gszvvmxsqcl0d74k5yz-libgpg-error-1.50/share /nix/store/ijdl5kgc40xkwdjzwlmf17w6yxrhyyq6-kservice-6.5.0/share /nix/store/swd2d1pc4r5bgj87zxkh0ax28kx0z28x-kjobwidgets-6.5.0/share /nix/store/ic14hwn5gfqy5s81kadph0qskqrfj97w-knotifications-6.5.0/share /nix/store/wg3qw25z1rihr830hnc80axac5337g74-kitemviews-6.5.0/share /nix/store/8vic35xc2ncy42277540xw9rj9g4s6df-kdoctools-6.5.0/share /nix/store/0l4a2mg6r9zzivnia4ddaf0zy4bwnid2-kcompletion-6.5.0/share /nix/store/874c7bilzdf3xr4fyiz9h2vqihj310ig-kbookmarks-6.5.0/share /nix/store/7ix5kji7frzbhjhlhfj6v3xizplpjp1k-kauth-6.5.0/share /nix/store/wcpa02nq9d3jpxw6pykj8khlbrvf4s2c-kwindowsystem-6.5.0/share /nix/store/f3c5k6v4dldsnixqfndbzq3c6q9amfhg-kfilemetadata-6.5.0/share /nix/store/h44h6473all3qkrjjhkm3v0fv63lqyms-libidn2-2.3.7/share /nix/store/z6mr5r2qs297lj8jy2vfy2p8qnsjy3sf-xz-5.6.2/share /nix/store/5yi4vwpx1321gmr90fxsw3qlq3b244bl-kdbusaddons-6.5.0/share /nix/store/hb1hkfsscqzqjfra32n99nf9wjwbq6hx-appstream-qt-1.0.3/share /nix/store/m1ykzddkgwz4w5b6zzghvqkzykbbl9rn-pipewire-1.2.2/share /nix/store/yl54l46w8n0yw2i1fnpk0m3chvj11v5a-libqalculate-5.2.0/share /nix/store/ql0rcvm5x0hy7wwlbwj2dyx17a7mxw6f-qqc2-desktop-style-6.5.0/share /nix/store/7chb7jxzkk3j30l0yz1489dxb918iji0-sonnet-6.5.0/share /nix/store/5kma93snq7jphs9s80iskhczlfqn1v5z-kirigami-6.5.0/share /nix/store/32la1z4byllm4ci5q4vl0j2w2hnkl2zy-kiconthemes-6.5.0/share /nix/store/8d1780gd681p992jjlil51g6v0adfgg1-kconfigwidgets-6.5.0/share /nix/store/7rqgyvpn01aspyjx6fjp8drsi5rxhsq4-kwidgetsaddons-6.5.0/share /nix/store/7jbwmfdqcgkzn7ms99hnvzfa912i7lj3-karchive-6.5.0/share /nix/store/7vcz5xwa48dymc5ph92qm83zrkzgi6p4-breeze-icons-6.5.0/share /nix/store/k7f40g0fqwmzdwbqnlh5ss18v73fp34b-kcoreaddons-6.5.0/share /nix/store/d4hfrza2csgr2nzgrbdqhh4n3hy6q8md-kcolorscheme-6.5.0/share /nix/store/6gfsg2hh7wzz1ms05ix9ik201y5clx7j-ki18n-6.5.0/share /nix/store/v6k9fn04xfhv74pv86s0k3bjdnz06382-kconfig-6.5.0/share /nix/store/xaq2rsh24p13m0d5g00szmiarhg3iy13-kcodecs-6.5.0/share /nix/store/pm0dm1g5hpcl9dpinqlzzkhf200jghp3-fontconfig-2.15.0-lib/share /nix/store/fs7lnqjn3zix2g3iz2b3ynf2m3rh4vcv-util-linux-2.39.4-lib/share /nix/store/mhq3m0gm80w8xxkbbkhds2gcm2k7y4fd-systemd-256.4/share /nix/store/7lr9qdizm42pf6clysg7syrky0si8aab-glib-2.80.4/share /nix/store/5i7vyd1n23g84fljnp9y80yvz6b7k9c4-gettext-0.21.1/share /nix/store/69gb9sv7fcl5v99fjl2j57acg37f1kw3-desktops/share /home/user/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /home/user/.nix-profile/share /nix/profile/share /home/user/.local/state/nix/profile/share /etc/profiles/per-user/user/share /nix/var/nix/profiles/default/share /run/current-system/sw/share`

**Comment by MarceColl** [comment]
@Reckfullies seems to have fixed this, can you try again @baduhai?
